version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  commands:
    - pwd
    - ls -alr

sphinx:
  builder: html
  configuration: ./docs/source/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - pyproject.toml


